<?php
/** @var Amasty\KrexsModule\Block\Form $block */
$cssClass = $this->hasCssClass() ? ' ' . $this->getCssClass() : '';
?>

<form class="<?= $cssClass; ?>">
    <label for="sku">SKU:</label>
    <input type="text" name="sku" id="sku">
    <?php if($block->getQtyFieldShowStatus()) {
        echo '<label for="qty">Quantity:</label>
              <input type="number" name="qty" id="qty" value="'. $block->getQtyValue() .'">';
    } ?>
    <div>
        <?= $block->getChildHtml() ?>
    </div>
    <input type="submit">
</form>
