<?php
/** @var Amasty\KrexsModule\Block\Form $block */
$cssClass = $block->hasCssClass() ? $block->getCssClass() : '';
?>

<form action="http://magento.loc/krex/cart/add" method="post" class="<?= $cssClass ?>"
      data-mage-init='{"validation": {"rules": {"sku": {"required":true}, "qty": {"required":true, "validate-greater-than-zero":true}}}}'>
    <label for="sku">SKU:</label>
    <input type="text" name="sku" id="sku">
    <?php if ($block->isShowQtyField()) : ?>
        <label for="qty">Quantity:</label>
        <input type="number" name="qty" id="qty" value="<?= $block->getQtyValue() ?>">
    <?php endif ?>
    <div>
        <?= $block->getChildHtml() ?>
    </div>
    <input type="submit">
</form>
